
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('trip_entries').del()
    .then(function () {
      // Inserts seed entries
      return knex('trip_entries').insert([
        {id: 1, user_id: 1, date:'03/31/18', trip_id:1, title:'Grand Canyon of Yellowstone', memory:'Bacon ipsum dolor amet ball tip frankfurter ham hock boudin tongue, pork belly swine t-bone pancetta sausage rump. Flank chicken spare ribs, biltong corned beef capicola turducken frankfurter pork loin. Biltong rump pastrami ham hock salami. Pastrami pig bresaola alcatra tail, buffalo cow drumstick jowl ball tip kielbasa ground round boudin burgdoggen pork loin. Bacon rump t-bone frankfurter meatball filet mignon. Bacon tail pork loin kielbasa alcatra. Prosciutto porchetta jowl hamburger, venison chicken fatback pork chop boudin ball tip kielbasa kevin turducken. Bacon shankle filet mignon, ham pig pork cow capicola hamburger. Chuck cupim turducken pork corned beef tail. Biltong chuck bresaola corned beef kevin pork chop andouille beef cupim short loin buffalo. Meatball pancetta hamburger biltong, cupim turducken brisket beef. Beef tenderloin rump pig pork chop tongue. Kevin shankle bresaola turducken landjaeger ribeye t-bone bacon burgdoggen. Hamburger pork loin andouille fatback brisket. Sirloin pork loin picanha, turkey ball tip pork chop tail. Venison tongue hamburger pancetta. Frankfurter meatball meatloaf buffalo doner prosciutto.'},
        {id: 2, user_id: 1, date:'01/04/18', trip_id:1, title:'Hot tub?', memory:'Bacon ipsum dolor amet ball tip frankfurter ham hock boudin tongue, pork belly swine t-bone pancetta sausage rump. Flank chicken spare ribs, biltong corned beef capicola turducken frankfurter pork loin. Biltong rump pastrami ham hock salami. Pastrami pig bresaola alcatra tail, buffalo cow drumstick jowl ball tip kielbasa ground round boudin burgdoggen pork loin. Bacon rump t-bone frankfurter meatball filet mignon. Bacon tail pork loin kielbasa alcatra. Prosciutto porchetta jowl hamburger, venison chicken fatback pork chop boudin ball tip kielbasa kevin turducken. Bacon shankle filet mignon, ham pig pork cow capicola hamburger. Chuck cupim turducken pork corned beef tail. Biltong chuck bresaola corned beef kevin pork chop andouille beef cupim short loin buffalo. Meatball pancetta hamburger biltong, cupim turducken brisket beef. Beef tenderloin rump pig pork chop tongue. Kevin shankle bresaola turducken landjaeger ribeye t-bone bacon burgdoggen. Hamburger pork loin andouille fatback brisket. Sirloin pork loin picanha, turkey ball tip pork chop tail. Venison tongue hamburger pancetta. Frankfurter meatball meatloaf buffalo doner prosciutto.'},
        {id: 3, user_id: 1, date:'02/14/17', trip_id:2, title:'Fat Cat', memory:'Cool Cat Murderface really digs being held and fuckin shit up. Bacon ipsum dolor amet ball tip frankfurter ham hock boudin tongue, pork belly swine t-bone pancetta sausage rump. Flank chicken spare ribs, biltong corned beef capicola turducken frankfurter pork loin. Biltong rump pastrami ham hock salami. Pastrami pig bresaola alcatra tail, buffalo cow drumstick jowl ball tip kielbasa ground round boudin burgdoggen pork loin. Bacon rump t-bone frankfurter meatball filet mignon. Bacon tail pork loin kielbasa alcatra. Prosciutto porchetta jowl hamburger, venison chicken fatback pork chop boudin ball tip kielbasa kevin turducken. Bacon shankle filet mignon, ham pig pork cow capicola hamburger. Chuck cupim turducken pork corned beef tail. Biltong chuck bresaola corned beef kevin pork chop andouille beef cupim short loin buffalo. Meatball pancetta hamburger biltong, cupim turducken brisket beef. Beef tenderloin rump pig pork chop tongue. Kevin shankle bresaola turducken landjaeger ribeye t-bone bacon burgdoggen. Hamburger pork loin andouille fatback brisket. Sirloin pork loin picanha, turkey ball tip pork chop tail. Venison tongue hamburger pancetta. Frankfurter meatball meatloaf buffalo doner prosciutto.'},
        {id:4, user_id:2, date:'324237',trip_id:3, title:'does it work', memory:'I really hope this works' },
      ]);
    })
    .then(()=>{
        return knex.raw(`SELECT setval('trip_entries_id_seq', (SELECT MAX(id) FROM trip_entries));`)
    })
};
